# Generated by Django 2.2 on 2019-04-14 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('color', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('studyset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.StudySet')),
            ],
            options={
                'unique_together': {('term', 'studyset')},
            },
        ),
    ]
