# Generated by Django 2.2 on 2019-04-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyset',
            name='is_public',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
