# Generated by Django 2.2 on 2019-04-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_auto_20190414_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='definition',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='card',
            name='term',
            field=models.CharField(max_length=50),
        ),
    ]
