# Generated by Django 2.2 on 2019-04-28 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20190424_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='color',
        ),
    ]
