# Generated by Django 2.2 on 2019-06-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_remove_card_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='definition',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='term',
            field=models.CharField(max_length=250),
        ),
    ]
